### ISSUE TITLE
selection long line breaks into multiple lines

### ISSUE THREAD

**Issue by tzws** [paolo-sz/fatty#5]
When I generate a JWT token, which is quite long, but needs to stick to ONE LINE.
If I redirect the output to a file, it's one line.
If I use minTTY, and selection the output, it one line.
If I use fatty, it always breaks the long line into multiple line when I select the output, and paste it into somewhere else, such as notepad.

**Comment by paolo-sz** [comment]
Did is the minTTY version you tried new enough (eg. 3.4.4)?
If you google a little you can see (at least this is my understanding) minTTY (latest versions) seems to be affected by the same issue.
Mine fatty is pretty aligned with minTTY code so I'm pretty surprised a behavior like this is happening in fatty but not in mintty.
I think the problem is related to ConPTY... and I cannot do anyting there...

Anyway, you need to provide a more detailed and reproducible case otherwise I have no chance to even start looking into the issue...

**Comment by tzws** [comment]
yes, you're right, minTTY (latest versions) seems to be affected by the same issue. git-bash version 3.16 also get affected.

[longline.zip](https://github.com/paolo-sz/fatty/files/6080656/longline.zip)

If I use cat the longline.js, it will output a single line.
if I use console.log() of node.js to print it out, it will breaks into multiple lines.

**Comment by tzws** [comment]
I solved this issue by writing to Windows clipboard directly using node.js
