### ISSUE TITLE
I have to type esc twice in vim to exit from insert mode to normal mode

### ISSUE THREAD

**Issue by jchain** [paolo-sz/fatty#6]
If I run mintty v3.5.2 directly, my vim is working fine when I type 'esc' key in insert mode. It will enter normal mode correctly. However, if I use your latest version of fatty, I noticed that I have to type twice the 'esc' key. The first type gets no response. Can you check if anywhere in the source code of fatty eats the 'esc' event?

**Comment by paolo-sz** [comment]
I'm not able to replicate the issue.
Just updated all the cygwin environment to the latest version and everything is fine here, insert mode terminates correctly at the first ESC...
Have you triedto update everything as well?
If not, do it and provide me a detailed description on how to replicate the issue, I will try to verify.
Once said that, I think in any case the issue is hardly related specifically to fatty... the terminal emulation is almost exactly the one of mintty so I'm expecting mintty should suffer the same issue (keep in mind that fatty master is currently aligned with mintty master which is something ahead of v3.5.2...).

**Comment by jchain** [comment]
It is weird. I can't reproduce it now. It happens sometimes in tmux session in fatty. I guess I should blame mintty.
